
CREATE TABLE ARTICLE
(
	ARTICLEID            VARCHAR(10) NOT NULL,
	DESCRIPTION          VARCHAR(200) NULL,
	TYPEID               VARCHAR(10) NOT NULL
);



ALTER TABLE ARTICLE
ADD PRIMARY KEY (TYPEID,ARTICLEID);



CREATE TABLE TYPE
(
	TYPEID               VARCHAR(10) NOT NULL,
	DESCRIPTION          VARCHAR(200) NULL
);



ALTER TABLE TYPE
ADD PRIMARY KEY (TYPEID);



ALTER TABLE ARTICLE
ADD FOREIGN KEY R_1 (TYPEID) REFERENCES TYPE (TYPEID);


